config/routes.rb
Rails.application.routes.draw do

  resources :people, only: [:index]

  get '/faq' => 'faq#index'
  get '/contact' => 'contact#index'
  get '/about' => 'about#index'
  get '/login' => redirect('/users/sign_in')

  resources :events
  resource :approve_users do
    get :index
    post :approve, on: :member
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :stories do
    member do
      post :pin
      post :unpin
      post :set_as_bio
      post :unset_as_bio
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  root 'home#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  default_scope { order "`events`.`from` DESC" }
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  default_scope { order('created_at desc') }
  after_create :set_permalink

  validates :title, presence: true

  serialize :tags, Array

  def to_param
    permalink
  end

  def set_permalink
    self.permalink = "#{id.to_s}-" + title.gsub(/\s+/,'-').gsub(/[^a-zA-Z0-9-]/,'').downcase
    self.save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :events
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    if !user_signed_in?
      render status: :unauthorized, text: 'Unauthorized. Please sign in.'
    elsif current_user && !current_user.approved?
      render status: :unauthorized, text: 'You account must be approved to modify contents on the site. Please contact hello@kek.org.in'
    end
  end
end

app/controllers/approve_users_controller.rb
class ApproveUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :find_unapproved_users

  def index
  end

  def approve
    @users.find(params[:id]).update_attribute(:approved, true)
    redirect_to approve_users_path
  end

  def destroy
    @users.find(params[:id]).destroy
    redirect_to approve_users_path
  end

  private

  def find_unapproved_users
    @users = User.where(approved: false)
  end

  def is_admin?
    unless current_user.role == 'admin'
      render status: :unauthorized, text: 'Unauthorized. Only admins can approve users.'
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = current_user.events.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description, :user_id, :from, :to, :location)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.where(['`to` > ?', DateTime.now])
    @stories = Story.all
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    bio_posts = Story.where("tags LIKE '%bio%'")

    @stories_pinned = bio_posts.where(pinned: true)
    @stories_unpinned = bio_posts.where(pinned: false)

    @stories = @stories_pinned + @stories_unpinned

    render 'stories/index'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy, :pin, :unpin, :set_as_bio, :unset_as_bio]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @stories = Story.all
    respond_with(@stories)
  end

  def show
    respond_with(@story)
  end

  def new
    @story = current_user.stories.new
    respond_with(@story)
  end

  def edit
  end

  def pin
    @story.update_attribute(:pinned, true)

    redirect_to people_path
  end

  def unpin
    @story.update_attribute(:pinned, false)

    redirect_to people_path
  end

  def set_as_bio
    @story.tags << "bio"
    @story.save

    redirect_to people_path
  end

  def unset_as_bio
    @story.tags -= ["bio"]
    @story.save

    redirect_to people_path
  end

  def create
    @story = current_user.stories.new(story_params)
    @story.save
    respond_with(@story)
  end

  def update
    @story.update(story_params)
    respond_with(@story)
  end

  def destroy
    @story.destroy
    respond_with(@story)
  end

  private
    def set_story
      @story = Story.where(permalink: params[:id]).first!
    end

    def story_params
      params.require(:story).permit(:title, :description)
    end

    def check_user
      if @story.user != current_user
        render text: 'You are a nasty cracker!'
      end
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_active_class(path)
    'nav-active' if request.path.include?(path)
  end
end

app/helpers/approve_users_helper.rb
module ApproveUsersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def extract_first_image(content)
    Nokogiri::HTML.fragment(content).search("img").first
  end

  def truncate_text(content, link_object)
    Nokogiri::HTML(content).text.
      truncate(100, omission: (link_to '.. read more', link_object)).
      html_safe
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/events/_form.html.haml
= simple_form_for(@event, html: { class: 'form-horizontal' }) do |f|
  = f.input :title, wrapper_html: { style: 'margin: 0' }
  %br
  = f.label :description
  = f.cktext_area :description
  = f.input :location, wrapper_html: { style: 'margin: 0' }
  = f.input :from
  = f.input :to

  %br
  = f.button :submit, class: 'btn btn-success'
  = link_to 'Cancel', stories_path, class: 'btn btn-default'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
.container
  .row
    .col-lg-12
      .main-heading
        - if user_signed_in?
          .pull-right.new-button
            = link_to 'New event', new_event_path, class: 'btn btn-default'
      %h2 Events
      .clearfix
      %br

      - if @events.empty?
        %p Bummer! No events to dislay. Check out later? :-)

      - @events.each do |event|
        .event{ class: "#{'reduce-opacity' if Date.today > event.to}" }
          .row
            .col-lg-1
              %i.fa.fa-calendar.calendar-icon{ style: 'font-size: 80px' }
            .col-lg-11
              %p.heading= event.title
              - if current_user && event.user == current_user
                %ul.list-inline
                  %li= link_to 'edit', edit_event_path(event)
                  |
                  %li= link_to 'delete', event, method: :delete, data: { confirm: 'Are  you sure?' }
              %strong
                = event.from.strftime('%e %b %Y %I:%M %p')
                to
                = event.to.strftime('%e %b %Y %I:%M %p')
              %p{ style: 'margin-top: 15px' }= event.description.html_safe
          %hr

app/views/events/new.html.haml
.container
  %h1 Add Event
  .row
    .col-lg-8
      = render 'form'

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Description:
  = @event.description
%p
  %b User:
  = @event.user_id
%p
  %b From:
  = @event.from
%p
  %b To:
  = @event.to

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/stories/_form.html.haml
= simple_form_for(@story, html: { class: 'form-horizontal' }) do |f|
  = f.input :title, wrapper_html: { style: 'margin: 0' }
  %br
  = f.label :description
  = f.cktext_area :description

  %br
  = f.button :submit, class: 'btn btn-success'
  = link_to 'Cancel', stories_path, class: 'btn btn-default'

app/views/stories/edit.html.haml
.container
  %h1 Edit Story
  .row
    .col-lg-8
      = render 'form'

app/views/stories/index.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .main-heading
        - if user_signed_in?
          .pull-right.new-button
            = link_to 'New story', new_story_path, class: 'btn btn-default'
        .clearfix
      - @stories.each do |story|
        .story
          = link_to story, class: 'title-link' do
            %p.heading= story.title
          %ul.list-inline.author-info
            %li
              %em{title: story.created_at}
                = story.user.name
                on
                = story.created_at.strftime('%e %b')
            - if story.user == current_user
              %li= link_to 'edit', edit_story_path(story)
              |
              %li= link_to 'delete', story, :method => :delete, :data => { :confirm => 'Are you sure?' }
            - if current_user.try(:role) == "admin"
              |
              %li
                - if story.tags.include?('bio')
                  = link_to 'Unset as bio', unset_as_bio_story_path(story), method: :post
                - else
                  = link_to 'Set as bio', set_as_bio_story_path(story), method: :post

              - if params[:controller] == 'people'
                |
                %li
                  - if story.pinned?
                    = link_to 'Unpin', unpin_story_path(story), method: :post
                  - else
                    = link_to 'Pin', pin_story_path(story), method: :post
          %br
          %p= truncate_html story.description.html_safe, length: 1200, omission: (link_to '.. read more', story)
          .clearfix
          - unless story == @stories.last
            %hr

app/views/stories/new.html.haml
.container
  %h1 Add Story
  .row
    .col-lg-8
      = render 'form'

app/views/stories/show.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .story.show-page
        = link_to @story, class: 'title-link' do
          %p.heading= @story.title
        %ul.list-inline.author-info
          %li
            %em{title: @story.created_at}
              = @story.user.name
              on
              = @story.created_at.strftime('%e %b')

          - if @story.user == current_user
            %li= link_to 'edit', edit_story_path(@story)
            |
            %li= link_to 'delete', @story, :method => :delete, :data => { :confirm => 'Are you sure?' }

      %p= @story.description.html_safe

      %br
      #disqus_thread

      %noscript
        Please enable JavaScript to view the
        %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments