config/routes.rb
Rails.application.routes.draw do

  resources :people, only: [:index]

  get '/faq' => 'faq#index'
  get '/contact' => 'contact#index'
  get '/about' => 'about#index'
  get '/login' => redirect('/users/sign_in')

  resources :events
  resource :approve_users do
    get :index
    post :approve, on: :member
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :stories do
    member do
      post :pin
      post :unpin
      post :set_as_bio
      post :unset_as_bio
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  default_scope { order "`events`.`from` DESC" }
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  default_scope { order('created_at desc') }
  after_create :set_permalink

  validates :title, presence: true

  serialize :tags, Array

  def to_param
    permalink
  end

  def set_permalink
    self.permalink = "#{id.to_s}-" + title.gsub(/\s+/,'-').gsub(/[^a-zA-Z0-9-]/,'').downcase
    self.save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :events
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    if !user_signed_in?
      render status: :unauthorized, text: 'Unauthorized. Please sign in.'
    elsif current_user && !current_user.approved?
      render status: :unauthorized, text: 'You account must be approved to modify contents on the site. Please contact hello@kek.org.in'
    end
  end
end

app/controllers/approve_users_controller.rb
class ApproveUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :find_unapproved_users

  def index
  end

  def approve
    @users.find(params[:id]).update_attribute(:approved, true)
    redirect_to approve_users_path
  end

  def destroy
    @users.find(params[:id]).destroy
    redirect_to approve_users_path
  end

  private

  def find_unapproved_users
    @users = User.where(approved: false)
  end

  def is_admin?
    unless current_user.role == 'admin'
      render status: :unauthorized, text: 'Unauthorized. Only admins can approve users.'
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = current_user.events.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description, :user_id, :from, :to, :location)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.where(['`to` > ?', DateTime.now])
    @stories = Story.all
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    bio_posts = Story.where("tags LIKE '%bio%'")

    @stories_pinned = bio_posts.where(pinned: true)
    @stories_unpinned = bio_posts.where(pinned: false)

    @stories = @stories_pinned + @stories_unpinned

    render 'stories/index'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy, :pin, :unpin, :set_as_bio, :unset_as_bio]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @stories = Story.all
    respond_with(@stories)
  end

  def show
    respond_with(@story)
  end

  def new
    @story = current_user.stories.new
    respond_with(@story)
  end

  def edit
  end

  def pin
    @story.update_attribute(:pinned, true)

    redirect_to people_path
  end

  def unpin
    @story.update_attribute(:pinned, false)

    redirect_to people_path
  end

  def set_as_bio
    @story.tags << "bio"
    @story.save

    redirect_to people_path
  end

  def unset_as_bio
    @story.tags -= ["bio"]
    @story.save

    redirect_to people_path
  end

  def create
    @story = current_user.stories.new(story_params)
    @story.save
    respond_with(@story)
  end

  def update
    @story.update(story_params)
    respond_with(@story)
  end

  def destroy
    @story.destroy
    respond_with(@story)
  end

  private
    def set_story
      @story = Story.where(permalink: params[:id]).first!
    end

    def story_params
      params.require(:story).permit(:title, :description)
    end

    def check_user
      if @story.user != current_user
        render text: 'You are a nasty cracker!'
      end
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_active_class(path)
    'nav-active' if request.path.include?(path)
  end
end

app/helpers/approve_users_helper.rb
module ApproveUsersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def extract_first_image(content)
    Nokogiri::HTML.fragment(content).search("img").first
  end

  def truncate_text(content, link_object)
    Nokogiri::HTML(content).text.
      truncate(100, omission: (link_to '.. read more', link_object)).
      html_safe
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/about/index.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .story.show-page
        %p.heading About

        %p
          Kovalam Ezhuthu Kalari is inspired from the old "Ezhuthu Kalari"
          traditions of Kerala. These educational spaces emphasised learning by
          doing, which is what we primarily love doing. We love to code, make, and
          play. In general, We do not like sitting in classrooms listening to
          lectures. If we have an idea, we start working on it, and people join in
          if they like it and are interested.

        %p Do you have an idea ? Come play with us!

        %p
          See our wiki here:
          = link_to 'wiki.kek.org.in', 'http://wiki.kek.org.in'

        %p
          We tweet here:
          = link_to '@kekorgin', 'https://twitter.com/kekorgin'

        %p
          Join our mailing list here:
          = link_to 'Kek-Friends', 'http://mail.kek.org.in/mailman/listinfo.cgi/friends'

app/views/approve_users/index.html.haml
.container
  .row
    .col-lg-12
      .main-heading
        %h1 Approve Users
      %ul
        - @users.each do |user|
          %li
            %h3
              = user.name
            %p= user.email
            = link_to 'Approve', approve_approve_users_path(id: user), method: :post, class: 'btn btn-default'
            = link_to 'delete', approve_users_path(id: user), method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure to delete the user?' }

app/views/contact/index.html.haml
.container
  .row
    .col-lg-12
      .main-heading
        %h1 Contact

        %p
          Email us at
          = link_to 'hello@kek.org.in', 'mailto:hello@kek.org.in'

        %h3 Map
        %iframe{:frameborder => "0", :height => "350", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "http://www.openstreetmap.org/export/embed.html?bbox=76.96433544158936%2C8.415637679573162%2C76.97888374328613%2C8.42934983646258&layer=mapnik&marker=8.422493818755951%2C76.97160959243774", :style => "border: 1px solid black", :width => "425"}
        %br/
        %small
          %a{:href => "http://www.openstreetmap.org/?mlat=8.4225&mlon=76.9716#map=16/8.4225/76.9716"} View Larger Map

        %br
        %br

        %p
          To reach KEK by bus from the city, one needs to board a south bound bus with any of the following destination boards:

        %p
          \- Peringamala via agricultural/karshika college
        %p
          \- Neyyattinkara
        %p
          \- Vizhinjam via Venganoor

        %br
        %p
          Your destination is west poonkulam and a landmark to ask for is the CGO Complex.

        %br
        %p
          At west poonkulam, also known as 'padinjarea poonkulam' ask for 'Varyam' house. It is a 100m walk from the bus stop.

app/views/faq/index.html.haml
.container
  .row
    .col-lg-12
      .main-heading
        %h1 FAQ
      .faqs
        %h4 What ?
        %p
          A space to experiment to develop local technology, methods and knowledge
          to apply to local problems.

        %h4 Who ?
        %p
          Are you a Hacker? Do you want to
          work on your own terms out of the buzz and smog of the city in a quiet
          place in an area of natural beauty ? Do you want to work on grassroots
          projects which impact the lives of local people around you ? Then that's
          who we are! :-)

        %h4 Why ?
        %p
          We're a group of tech refugees who fled the cities to the Himalayas to
          get away from it all. We found a way to make it work. And we now want to
          bring the goodness of our experience back to the rest of the country!

        %h4 How do I join you ?
        %p
          Come around and visit us on Open Days (Thursdays) for chaya or kappee
          after working hours (4pm). You'll bump into one of the current
          residents.
        %p OR, if you're far away,
        %p
          Email us at
          = link_to 'hello@kek.org.in', 'mailto:hello@kek.org.in'
        %p OR
        %p
          Follow us on twitter at
          = link_to 'twitter.com/kekorgin', 'https://twitter.com/kekorgin'
        %h4 What about the copyright to my work ?
        Your work is yours - we don't want to hold on to anything you work
        on. We do however ask that you post weekly on our community blog, so
        that other people can know what you're working on and collaborate with
        you.

        %h4 How long can I stay ?
        %p
          Residencies are expected to be on specific projects for a clear period
          of time. We do not encourage residencies longer than 6months. For longer
          periods of time, you could become a resident Alumnus, and we'll help you
          find local accommodation nearby.

        %h4 How much does it cost ?
        %p
          Residencies are funded through a gift economy. Currently
          Rs. 8000/month is a useful reference figure.  If you can
          afford more, it will help defray the cost of other residents
          who can't afford this now. And if you can't afford to pay this
          much, please email us, we can talk about other ways you can
          contribute, outside of money - for eg: you could work extra
          in the vegetable garden, help us build useful things,
          fix things that are broken, or cook meals etc.

        %p
          You will have access to a bedroom with a bathroom attached,
          fast internet, a functional kitchen, and any other common
          facilities on the property.

        %p Shorter stays are possible, but please get in touch with us first.

        %h4 What kind of food will I get ?
        %p
          Kerala has a range of tasty and novel cuisine.
          However, we provide simple vegetarian meals.

          If you want to sample other options, there are a number of
          restaurants and bars in vicinity, especially closer to the
          beach.

          If you want to cook your own, the kitchen is available for
          this.

          We are an alcohol free space (see below).

        %h4 What kind of etiquette should I be mindful of ?
        %p
          Since we're an educational space, and working amongst
          vulnerable young people and communities, we have to be very
          mindful of our behaviour, both in and out of the space.

          In general, the guiding principle is to be excellent towards
          each other. This means, for example, using the designated
          areas for smoking, making sure the space is clean, putting
          things in order if you find them messy (eg: doing the dishes
          if you find the sink has some), using civil language, wearing
          locally acceptable clothing, etc.

        %h4 What else can I do in the area ?
        %p
          We're within 2km of the ocean and beach - which means you can easily
          find your way to the beach. We work closely with the Kovalam Surf club
          and the Kovalam Skate club. We also work very closely with a local
          charity (
          = link_to 'www.sisp.in', 'http://www.sisp.in'
          ) in their local social charitable efforts.

app/views/home/_recent_events.html.haml
.col-lg-4.col-sm-6
  .panel.panel-default
    .panel-heading
      %h3.panel-title Events
    .panel-body
      - if @events.empty?
        %p
        No new events to display. Click
        = link_to 'here', events_path
        for past events.
      - @events.each do |event|
        .event-info
          .media
            .media-left.pull-left
              %i.fa.fa-calendar.calendar-icon{ style: 'font-size: 44px' }

            .media-body.recent-event
              %h4.media-heading= event.title
              %p
                %i.fa.fa-clock-o
                - if event.from.to_date == event.to.to_date
                  = event.from.strftime('%e %b')
                  = event.from.strftime('%I:%M %p')
                - else
                  = event.from.strftime('%e %b')
                  to
                  = event.to.strftime('%e %b')
                %br
                - if event.location.present?
                  %i.fa.fa-map-marker
                  = event.location

app/views/home/_recent_stories.html.haml
.col-lg-4.col-sm-6
  .panel.panel-default
    .panel-heading
      %h3.panel-title Recent stories
    .panel-body
      - @stories.each do |story|
        .story-info
          .media
            .media-left
              = link_to story, class: 'pull-left' do
                - if (img = extract_first_image(story.description))
                  = image_tag img.attributes['src'].value, height: '64px', width: '64px', class: 'img-rounded'
                - else
                  %i.fa.fa-picture-o{ style: 'font-size: 64px; color: rgba(175, 164, 164, 0.39);' }

            .media-body.recent-story
              %h4.media-heading.story-panel-heading
                = link_to story.title, story
              %p= truncate_text(story.description, story)
        %br

app/views/home/index.html.haml
.intro-header
  .container
    .row
      .col-lg-12
        .intro-message
          %h2 കോവളം എഴുത്തു കളരി
          %h2 Kovalam Ezhuthu Kalari
          %hr.intro-divider/
          %ul.list-inline
            %li
              = link_to about_path, class: 'btn btn-primary btn-lg' do
                %span
                  Read more

.content-section-a
  .container
    .row
      = render 'recent_stories'
      = render 'recent_events'

      .col-lg-4.col-sm-6
        %a{class: "twitter-timeline", href: "https://twitter.com/kekorgin", data: {'widget-id' => "633865879634100224"}} Tweets by @kekorgin

app/views/people/index.html.haml
%h1 People#index
%p Find me in app/views/people/index.html.haml