config/routes.rb
Rails.application.routes.draw do

  resources :people, only: [:index]

  get '/faq' => 'faq#index'
  get '/contact' => 'contact#index'
  get '/about' => 'about#index'
  get '/login' => redirect('/users/sign_in')

  resources :events
  resource :approve_users do
    get :index
    post :approve, on: :member
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :stories do
    member do
      post :pin
      post :unpin
      post :set_as_bio
      post :unset_as_bio
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  default_scope { order "`events`.`from` DESC" }
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  default_scope { order('created_at desc') }
  after_create :set_permalink

  validates :title, presence: true

  serialize :tags, Array

  def to_param
    permalink
  end

  def set_permalink
    self.permalink = "#{id.to_s}-" + title.gsub(/\s+/,'-').gsub(/[^a-zA-Z0-9-]/,'').downcase
    self.save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :events
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    if !user_signed_in?
      render status: :unauthorized, text: 'Unauthorized. Please sign in.'
    elsif current_user && !current_user.approved?
      render status: :unauthorized, text: 'You account must be approved to modify contents on the site. Please contact hello@kek.org.in'
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = current_user.events.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :description, :user_id, :from, :to, :location)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.where(['`to` > ?', DateTime.now])
    @stories = Story.all
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    bio_posts = Story.where("tags LIKE '%bio%'")

    @stories_pinned = bio_posts.where(pinned: true)
    @stories_unpinned = bio_posts.where(pinned: false)

    @stories = @stories_pinned + @stories_unpinned

    render 'stories/index'
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy, :pin, :unpin, :set_as_bio, :unset_as_bio]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @stories = Story.all
    respond_with(@stories)
  end

  def show
    respond_with(@story)
  end

  def new
    @story = current_user.stories.new
    respond_with(@story)
  end

  def edit
  end

  def pin
    @story.update_attribute(:pinned, true)

    redirect_to people_path
  end

  def unpin
    @story.update_attribute(:pinned, false)

    redirect_to people_path
  end

  def set_as_bio
    @story.tags << "bio"
    @story.save

    redirect_to people_path
  end

  def unset_as_bio
    @story.tags -= ["bio"]
    @story.save

    redirect_to people_path
  end

  def create
    @story = current_user.stories.new(story_params)
    @story.save
    respond_with(@story)
  end

  def update
    @story.update(story_params)
    respond_with(@story)
  end

  def destroy
    @story.destroy
    respond_with(@story)
  end

  private
    def set_story
      @story = Story.where(permalink: params[:id]).first!
    end

    def story_params
      params.require(:story).permit(:title, :description)
    end

    def check_user
      if @story.user != current_user
        render text: 'You are a nasty cracker!'
      end
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_active_class(path)
    'nav-active' if request.path.include?(path)
  end
end

app/helpers/approve_users_helper.rb
module ApproveUsersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def extract_first_image(content)
    Nokogiri::HTML.fragment(content).search("img").first
  end

  def truncate_text(content, link_object)
    Nokogiri::HTML(content).text.
      truncate(100, omission: (link_to '.. read more', link_object)).
      html_safe
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .row
      .col-lg-12
        %div{class: ('footer-content' unless request.path == '/' )}
          .pull-right
            %p hello@kek.org.in
          %p (C) 2015 kek.org.in

app/views/layouts/_navbar.html.haml
%navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/"}
        %i.fa.fa-home
        KEK
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Stories", stories_path, class: set_active_class(stories_path)
        %li
          = link_to "People", people_path, class: set_active_class(people_path)

        / %li
        /   %a{href: "#"} People
        %li
          = link_to 'Events', events_path, class: set_active_class(events_path)
        %li
          = link_to 'FAQ', faq_path, class: set_active_class(faq_path)
        %li
          = link_to 'Contact', contact_path, class: set_active_class(contact_path)
        %li
          = link_to 'About', about_path, class: set_active_class(about_path)

        - if user_signed_in?
          - if current_user.role == 'admin'
            %li
              = link_to 'Approve users', approve_users_path
          %li
            = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Login', new_user_session_path, class: set_active_class(new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %title Kovalam Ezhuthu Kalari (കോവളം എഴുത്തു കളരി)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic", rel: "stylesheet", type: "text/css"}/
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    = render 'layouts/navbar'
    = yield
    = render 'layouts/footer'